In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[13, 4]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[8, 22],
 [13, 4],
 [22, 19],
 [21, 23, 27],
 [1, 9, 16],
 [14, 22],
 [14, 9, 16],
 [29, 14],
 [29, 1],
 [26, 10]]

In [5]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding = "post")
padded_reviews

array([[ 8, 22,  0],
       [13,  4,  0],
       [22, 19,  0],
       [21, 23, 27],
       [ 1,  9, 16],
       [14, 22,  0],
       [14,  9, 16],
       [29, 14,  0],
       [29,  1,  0],
       [26, 10,  0]])

In [6]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [9]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 1s 511ms/step - loss: 0.6328 - accuracy: 1.0000


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]


array([-0.06754313,  0.00773684,  0.0932306 , -0.01454328, -0.05404   ],
      dtype=float32)

In [14]:
weights[4]

array([-0.06848548,  0.0017911 , -0.06276397, -0.00220848, -0.0594401 ],
      dtype=float32)

In [15]:
weights[16]

array([-0.04586509, -0.00521277,  0.03018461,  0.00763082, -0.00431042],
      dtype=float32)